{{- if and .Values.proxy.enabled .Values.proxy.ingress.enabled }}
apiVersion: {{ include "zentinel.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "zentinel.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  {{- with .Values.proxy.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.proxy.ingress.className (eq (include "zentinel.ingress.isStable" .) "true") }}
  ingressClassName: {{ .Values.proxy.ingress.className }}
  {{- end }}
  {{- if .Values.proxy.ingress.tls }}
  tls:
    {{- range .Values.proxy.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.proxy.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if eq (include "zentinel.ingress.supportsPathType" $) "true" }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if eq (include "zentinel.ingress.isStable" $) "true" }}
              service:
                name: {{ include "zentinel.fullname" $ }}-proxy
                port:
                  number: {{ $.Values.proxy.service.httpPort }}
              {{- else }}
              serviceName: {{ include "zentinel.fullname" $ }}-proxy
              servicePort: {{ $.Values.proxy.service.httpPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
