{{- if and .Values.proxy.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "zentinel.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "zentinel.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zentinel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy
{{- end }}
