{{- if .Values.proxy.enabled }}
{{- if not .Values.proxy.config.externalConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zentinel.fullname" . }}-proxy-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
data:
  config.kdl: |
    {{- .Values.proxy.config.kdl | nindent 4 }}
{{- end }}
{{- end }}
